# Docker cookbook helpers.
# Targets:
#   make build       - build every Dockerfile variant
#   make sizes       - build then print a markdown size table
#   make sizes.md    - write the table into SIZES.md
#   make clean       - remove all cookbook-* images
#
# Variant naming convention: cookbook-<stack>[-variant]

VARIANTS := \
  go:go/Dockerfile \
  go-distroless:go/Dockerfile.distroless \
  go-scratch:go/Dockerfile.scratch \
  python:python/Dockerfile \
  python-distroless:python/Dockerfile.distroless \
  node:node/Dockerfile \
  node-distroless:node/Dockerfile.distroless \
  java:java/Dockerfile \
  java-distroless:java/Dockerfile.distroless \
  react:react/Dockerfile \
  react-scratch:react/Dockerfile.scratch \
  rust:rust/Dockerfile \
  rust-distroless:rust/Dockerfile.distroless \
  bun:bun/Dockerfile \
  dotnet:dotnet/Dockerfile

.PHONY: build sizes sizes.md clean

build:
	@set -e; \
	for entry in $(VARIANTS); do \
	  name=$${entry%%:*}; dockerfile=$${entry##*:}; \
	  ctx=$$(dirname $$dockerfile); \
	  echo ">> building cookbook-$$name from $$dockerfile"; \
	  docker build -t cookbook-$$name -f $$dockerfile $$ctx; \
	done

sizes: build
	@echo ""
	@echo "| Image | Size |"
	@echo "|-------|------|"
	@docker images --format '{{.Repository}} {{.Size}}' \
	  | grep '^cookbook-' \
	  | sort \
	  | awk '{ printf "| %s | %s |\n", $$1, $$2 }'

sizes.md: build
	@{ \
	  echo "# Measured image sizes"; \
	  echo ""; \
	  echo "Generated by 'make sizes.md' against the sample apps in this repo."; \
	  echo ""; \
	  echo "| Image | Size |"; \
	  echo "|-------|------|"; \
	  docker images --format '{{.Repository}} {{.Size}}' \
	    | grep '^cookbook-' \
	    | sort \
	    | awk '{ printf "| %s | %s |\n", $$1, $$2 }'; \
	} > SIZES.md
	@echo "wrote SIZES.md"

clean:
	@docker images --format '{{.Repository}}' | grep '^cookbook-' | xargs -r docker rmi -f
