#!/usr/bin/env bash
# bench.sh — measure cold start, RSS, and throughput for every cookbook image.
#
# Requires: docker, curl, awk.
# Optional: hey (https://github.com/rakyll/hey) for throughput; falls back to a
# simple curl loop if hey isn't installed.
#
# Usage:
#   ./scripts/bench.sh                  # bench every cookbook-* image, write BENCHMARKS.md
#   ./scripts/bench.sh cookbook-go      # bench one image
#
# Notes:
#   - Numbers are local-laptop class. Re-run in your target env for real data.
#   - Cold start = time from `docker run` until /health returns 200.

set -euo pipefail

if [ $# -gt 0 ]; then
    IMAGES=( "$@" )
else
    # Portable line-split (macOS bash 3.2 has no mapfile).
    IMAGES=()
    while IFS= read -r line; do
        IMAGES+=( "$line" )
    done < <(docker images --format '{{.Repository}}' | grep '^cookbook-' | sort -u)
fi

# Each image needs to know which port its sample app exposes.
port_for() {
    case "$1" in
        cookbook-go|cookbook-go-distroless|cookbook-go-scratch) echo 8080 ;;
        cookbook-python|cookbook-python-distroless) echo 8000 ;;
        cookbook-node|cookbook-node-distroless) echo 3000 ;;
        cookbook-java|cookbook-java-distroless) echo 8080 ;;
        cookbook-react|cookbook-react-scratch) echo 3000 ;;
        cookbook-rust|cookbook-rust-distroless) echo 8080 ;;
        cookbook-bun|cookbook-bun-distroless) echo 3000 ;;
        cookbook-dotnet) echo 8080 ;;
        *) echo 8080 ;;
    esac
}

# Each image's health endpoint.
health_path_for() {
    case "$1" in
        cookbook-java|cookbook-java-distroless) echo /actuator/health ;;
        *) echo /health ;;
    esac
}

bench_one() {
    local image="$1"
    local cport host_port hp cid t0 t1 cold_ms rss_kb rss_mb rps

    cport=$(port_for "$image")
    hp=$(health_path_for "$image")
    host_port=$(( ( RANDOM % 10000 ) + 40000 ))

    echo ">> $image  (host:$host_port → container:$cport, health=$hp)"

    # Cold start
    t0=$(python3 -c 'import time; print(int(time.time()*1000))')
    cid=$(docker run -d -p "${host_port}:${cport}" "$image")
    until curl -fsS "http://localhost:${host_port}${hp}" >/dev/null 2>&1; do
        if [ "$(( $(python3 -c 'import time; print(int(time.time()*1000))') - t0 ))" -gt 90000 ]; then
            echo "   timeout waiting for $image"
            docker logs "$cid" 2>&1 | tail -20
            docker rm -f "$cid" >/dev/null 2>&1 || true
            cold_ms="timeout"
            break
        fi
        sleep 0.1
    done
    if [ -z "${cold_ms:-}" ]; then
        t1=$(python3 -c 'import time; print(int(time.time()*1000))')
        cold_ms=$(( t1 - t0 ))
    fi

    # RSS (after warm-up: send 100 requests, then sample)
    if [ "$cold_ms" != "timeout" ]; then
        for _ in $(seq 1 100); do
            curl -s -o /dev/null "http://localhost:${host_port}${hp}" || true
        done
        rss_kb=$(docker stats --no-stream --format '{{.MemUsage}}' "$cid" | awk -F'[ /]' '{print $1}')
        # Convert "12.34MiB" → MB rounded
        rss_mb=$(python3 -c "
v='$rss_kb'
import re
m=re.match(r'([0-9.]+)([a-zA-Z]+)', v)
if not m: print('n/a'); raise SystemExit
n=float(m.group(1)); u=m.group(2).lower()
mult={'kib':1/1024,'mib':1,'gib':1024,'kb':1/1024,'mb':1,'gb':1024}.get(u,1)
print(f'{n*mult:.1f}')
")

        # Throughput: 10s / 50 concurrent if hey is installed, else simple loop
        if command -v hey >/dev/null 2>&1; then
            rps=$(hey -z 10s -c 50 "http://localhost:${host_port}${hp}" 2>/dev/null \
                  | awk '/Requests\/sec/{print int($2)}')
        else
            # Fallback: 1000 sequential requests
            t0=$(python3 -c 'import time; print(int(time.time()*1000))')
            for _ in $(seq 1 1000); do
                curl -s -o /dev/null "http://localhost:${host_port}${hp}"
            done
            t1=$(python3 -c 'import time; print(int(time.time()*1000))')
            rps=$(( 1000 * 1000 / (t1 - t0 + 1) ))
        fi
    else
        rss_mb="n/a"; rps="n/a"
    fi

    docker rm -f "$cid" >/dev/null 2>&1 || true

    printf '| %s | %s ms | %s MB | %s req/s |\n' \
        "$image" "$cold_ms" "$rss_mb" "$rps" >> "$RESULTS_FILE"
}

RESULTS_FILE="$(mktemp)"
trap 'rm -f "$RESULTS_FILE"' EXIT

echo "# Local benchmark results" > BENCHMARKS.md
{
    echo ""
    echo "Generated by \`scripts/bench.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo ""
    echo "Numbers reflect this host's CPU/IO and a single warm-up. Re-run in your"
    echo "target environment for production-relevant data. Cold start measures"
    echo "\`docker run\` → first \`/health\` 200."
    echo ""
    echo "| Image | Cold start | RSS (warm) | Throughput |"
    echo "|-------|-----------|------------|------------|"
} >> BENCHMARKS.md

for img in "${IMAGES[@]}"; do
    bench_one "$img" || true
done

cat "$RESULTS_FILE" >> BENCHMARKS.md
echo ""
echo "wrote BENCHMARKS.md"
